version: '3.8'

# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  mcp-hub:
    restart: always
    environment:
      # Production: secure API key required!
      - MCP_HUB_API_KEY=${MCP_HUB_API_KEY:-change-me-in-prod}
      - MCP_HUB_LOG_LEVEL=warning
    volumes:
      # Production: only bind config and logs, no source code mounting
      - ./config:/app/config:ro
      - ./logs:/app/logs
      # To enable git server, mount a real repo:
      # - /absolute/path/to/your/repo:/repo:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # Additional production-specific health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "--max-time", "5"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Add production logging driver if needed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: [
      "--config", "/app/config/config.json",
      "--port", "8000",
      "--api-key", "${MCP_HUB_API_KEY:-change-me-in-prod}",
      "--strict-auth"
    ]
