version: '3.8'

services:
  mcp-hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MCP_HUB_API_KEY=${MCP_HUB_API_KEY:-default-api-key}
      - MCP_HUB_LOG_LEVEL=warning
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      # Uncomment the next line if you use the git server and want to mount a repo
      # - /caminho/para/seu/repo:/repo:ro
    networks:
      - mcp-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Tip: to enable config hot-reload inside the container, add "--hot-reload" below
    command: [
      "--config", "/app/config/config.json",
      "--port", "8000",
      "--api-key", "${MCP_HUB_API_KEY:-default-api-key}",
      "--log-level", "${MCP_HUB_LOG_LEVEL:-warning}"
    ]

networks:
  mcp-network:
    driver: bridge
