version: '3.8'

services:
  mcp-hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Defina MCP_HUB_API_KEY no .env para produção segura!
      - MCP_HUB_API_KEY=${MCP_HUB_API_KEY:-change-me-in-prod}
      - MCP_HUB_LOG_LEVEL=warning
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      # Para usar o servidor git, monte um repositório real:
      # - /caminho/absoluto/para/seu/repo:/repo:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "--max-time", "5"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    command: [
      "--config", "/app/config/config.json",
      "--port", "8000",
      "--api-key", "${MCP_HUB_API_KEY:-change-me-in-prod}",
      "--strict-auth"
    ]


