name: CI - Unit Tests (on Release)

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev
      - name: Diagnostic: python & pip
        run: |
          python --version
          python -c "import sys; print(sys.executable)"
          pip --version

      - name: Install Poetry (if needed)
        run: |
          pip install --upgrade pip setuptools wheel
          pip install poetry || true

      - name: Install project (editable)
        run: |
          pip install --upgrade pip setuptools wheel
          # install package in editable mode so tests run against workspace
          pip install -e .

      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov fastapi starlette watchdog passlib typer uvicorn python-dotenv pyjwt mcp
      - name: Run unit tests with coverage
        run: |
          PYTHONPATH=src pytest --cov=src/mcp_hub tests/unit --cov-report=term-missing -v

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
