name: CI - Unit Tests (on Release)

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          check-latest: true
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-dev
      - name: Diagnostic - python & pip
        run: |
          python --version
          python -c "import sys; print(sys.executable)"
          pip --version
          which python
          ls -la /opt/hostedtoolcache/Python/

      - name: Install Poetry (if needed)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install poetry || true

      - name: Install project (editable)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # install package in editable mode so tests run against workspace
          python -m pip install -e .

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          # project dependencies are installed by the editable install above; only install test/runtime tools here
          python -m pip install pytest pytest-asyncio pytest-cov
      - name: Run unit tests with coverage
        run: |
          PYTHONPATH=src python -m pytest --cov=src/mcp_hub tests/unit --cov-report=term-missing -v

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
